/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline;

import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class Cancellation extends javax.swing.JFrame {

    /**
     * Creates new form Cancellation
     */
    public Cancellation() {
        initComponents();
        GetTicket();
        txtFCode.setEditable(false);
        DisplayCanc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbID = new javax.swing.JComboBox<>();
        txtFCode = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        bntReset = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Date = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CancelTbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MyCodeSpace Airline");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 298, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ticket ID");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 124, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelled (1).png"))); // NOI18N
        jLabel7.setText("Ticket Cancellation");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 325, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Flight Code");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 129, -1));

        cbID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIDActionPerformed(evt);
            }
        });
        jPanel2.add(cbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 151, 36));

        txtFCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txtFCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 162, 40));

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Flight Code");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, 126, -1));

        btnBook.setBackground(new java.awt.Color(204, 204, 0));
        btnBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBook.setForeground(new java.awt.Color(204, 204, 204));
        btnBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelled.png"))); // NOI18N
        btnBook.setText("Cancel");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        jPanel2.add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 100, 120, 34));

        btnBack.setBackground(new java.awt.Color(204, 204, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(204, 204, 204));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 260, 120, 34));

        bntReset.setBackground(new java.awt.Color(204, 204, 0));
        bntReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bntReset.setForeground(new java.awt.Color(204, 204, 204));
        bntReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reset.png"))); // NOI18N
        bntReset.setText("Reset");
        bntReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntResetActionPerformed(evt);
            }
        });
        jPanel2.add(bntReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 180, 120, 34));

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/list.png"))); // NOI18N
        jLabel12.setText("Cancellation List");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 280, 70));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 10, 37, -1));
        jPanel2.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 220, 176, 36));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kawai.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 400));

        CancelTbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CancelTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        CancelTbl.setRowHeight(25);
        CancelTbl.setSelectionBackground(new java.awt.Color(255, 0, 0));
        jScrollPane1.setViewportView(CancelTbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 493, 1240, 250));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dubai1 airport1.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 360, 1480, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Main().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnBackActionPerformed
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null, rsl = null;
    Statement st = null, stl = null;

    private void GetTicket() {
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
            st = con.createStatement();
            String Query = "select * from bookingtbl";
            rs = st.executeQuery(Query);
            while (rs.next()) {
               String TID =String.valueOf(rs.getInt("TicketID")) ;
                cbID.addItem(TID);

            }
        } catch (Exception e) {
        }
    }

    private void GetFCode() {
        String Query = "select * from bookingtbl where TicketID = " + cbID.getSelectedItem().toString();
        Statement st;
        ResultSet rs;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
            st = con.createStatement();
            rs = st.executeQuery(Query);
            if (rs.next()) {
                txtFCode.setText(rs.getString("FlCode"));
            }
        } catch (Exception e) {
        }
    }

    private void DisplayCanc() {
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
            st = con.createStatement();
            rs = st.executeQuery("select * from cancellationtbl");
            CancelTbl.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
        }
    }
    int CId = 0;

    private void CountCanc() {
        try {
            stl = con.createStatement();
            rsl = stl.executeQuery("select Max(CancID)from cancellationtbl");
            rsl.next();
            CId = rsl.getInt(1) + 1;

        } catch (Exception e) {
        }
    }
    private void bntResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntResetActionPerformed
        txtFCode.setText("");
    }//GEN-LAST:event_bntResetActionPerformed

    private void cbIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIDActionPerformed
       GetFCode();
    }//GEN-LAST:event_cbIDActionPerformed
    private void Cancel(){
        try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb", "root", "");
                String Query = "Delete from bookingtbl where TicketID = " + cbID.getSelectedItem() ;
                Statement Del = con.createStatement();
                Del.executeUpdate(Query);
                //JOptionPane.showMessageDialog(this, "Flight delete successful!");
                //DisplayFlights();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
    }
    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        if(txtFCode.getText().isEmpty() ){
           JOptionPane.showMessageDialog(this, "Missing Information");
       }else{
           try {
               CountCanc();
               
               con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinedb","root","");
               PreparedStatement Add = con.prepareStatement("insert into cancellationtbl values(?,?,?,?)");
               Add.setInt(1, CId);
               Add.setInt(2, Integer.valueOf(cbID.getSelectedItem().toString()) );
               Add.setString(3, txtFCode.getText());
               Add.setString(4, Date.getDate().toString());
             
               int row = Add.executeUpdate();
               JOptionPane.showMessageDialog(this, "Ticket Cancelled Successful!");
               con.close();
               Cancel();
               DisplayCanc();
               GetTicket();
               //Clear();
               
           } catch (Exception e) {
               JOptionPane.showMessageDialog(this, e);
           }
       }
    }//GEN-LAST:event_btnBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancellation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CancelTbl;
    private com.toedter.calendar.JDateChooser Date;
    private javax.swing.JButton bntReset;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBook;
    private javax.swing.JComboBox<String> cbID;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtFCode;
    // End of variables declaration//GEN-END:variables
}
